#!/usr/bin/env bash

# Dynamically take input from STDIN or args
input=${1--}

# Shift argument before parsing flags
OPTIND=2

# Temporary buffers
call_graph=$(mktemp)
dep_graph=$(mktemp)

# By default, suppress GraphViz output
graph_out=/dev/null

# Ensure proper cleanup
trap 'rm -f "$call_graph" "$dep_graph"; exit' 0 2 3 15

# Parse verbosity flags
while getopts ":av" opt; do
    case $opt in
        a)
            # Track all symbols
            flag='-ix'
            ;;
        v)
            # Output intermediate steps
            verbose=true
            graph_out=graph.gv
            ;;
        [?])
            # Print usage upon unknown
            echo "Usage: $0 [-a] [-v]"
            echo "Generate topological sort for C/C++ source file"
            echo
            echo "Options"
            echo "-a,    output all symbols (external, static, typedef)"
            echo "-v,    verbose output (print intermediate representations)"
            echo "       and generate GraphViz dependency graph dot/gv file"
            exit 1
            ;;
    esac
done

# Create the reverse call graph using cflow first.
cflow -r $flag <(cat "$input") > "$call_graph" 2> /dev/null

# Print call graph if verbose
if [ "$verbose" = true ]; then
    echo "Call graph:"
    cat $call_graph
    echo ""
fi

# Create dependency graph
./dep.py "$call_graph" "$dep_graph" 1> $graph_out

# Print dependency graph if verbose
if [ "$verbose" = true ]; then
    echo "Dependency graph:"
    cat $dep_graph
    echo ""
fi

# Topological sort
if [ "$verbose" = true ]; then
    echo "Topological sort:"
fi

tsort < "$dep_graph"
